---
- name: "Join Domain"
  hosts: win
  gather_facts: no
  tasks:
  - ansible.windows.win_domain_membership:
      dns_domain_name: forest.com
      hostname: server102
      domain_admin_user: administrator@forest.com
      domain_admin_password: AndroidMark#3
      domain_ou_path: "OU=servers,DC=FOREST,DC=COM"
      state: domain
    register: domain_state

  - name: "Reboot after domain join"
    ansible.windows.win_reboot:
      when: domain_state.reboot_required

  - name: "Promote DC"
    win_domain_controller:
      dns_domain_name: forest.com
      domain_admin_user: administrator@forest.com
      domain_admin_password: AndroidMark#3
      safe_mode_password: AndroidMark#3
      state: domain_controller
      register: dc_promotion

- name: "Reboot after promotion"
  ansible.windows.win_reboot:
    when: dc_promotion.reboot_required
