---
- hosts: localhost
  connection: local
  vars_prompt:
    - name: githubRepo
      prompt: Enter Github Repo to connect repo to container

- name: Create a resource group
  azure_rm_resourcegroup:
    name: myResourceGroup
    location: westus

- name: Create sample container group with azure file share volume
  azure_rm_containerinstance:
    resource_group: myResourceGroup
    name: myContainerInstanceGroupz
    os_type: linux
    ip_address: public
    containers:
      - name: container1
        image: httpd
        memory: 
        volume_mounts:
          - name: repoVolume
            mount_path: "/data/repo"
        ports:
          - 80
          - 81
    volumes:
      - name: repoVolume
        git_repo:
          repository: {{githubRepo}}