---
- hosts: icx
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_user: 
    ansible_become: True
    ansible_password: 
    ansible_become_method: enable
    ansible_become_pass: 
    ansible_command_timeout: 80
  tasks:
  - name: reboot switches
    commscope.icx.icx_vlan:
      vlan_id: 150
