---
- name: "Join Domain"
  hosts: win
  gather_facts: no
  tasks:
  - ansible.windows.win_domain_membership:
      dns_domain_name: "{{ dns_domain_name }}"
      hostname: "{{ hostname }}"
      domain_admin_user: "{{  domain_admin_user }}"
      domain_admin_password: "{{ domain_admin_password }}"
      domain_ou_path: "{{ domain_ou_path }}"
      state: domain
    register: domain_state

  - name: "Reboot after domain join"
    ansible.windows.win_reboot:
      when: domain_state.reboot_required

  - name: "Promote DC"
    win_domain_controller:
      dns_domain_name: "{{ dns_domain_name }}"
      domain_admin_user: "{{ domain_admin_user }}"
      domain_admin_password: "{{ domain_admin_password }}"
      safe_mode_password: "{{ safe_mode_password }}"
      state: domain_controller
      register: dc_promotion

- name: "Reboot after promotion"
  ansible.windows.win_reboot:
    when: dc_promotion.reboot_required
